# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `soren` gem.
# Please instead update this file by running `bin/tapioca gem soren`.


# source://soren//lib/soren/core_ext/blank.rb#4
class Object < ::BasicObject
  include ::Kernel
  include ::PP::ObjectMixin
end

# source://soren//lib/soren/version.rb#3
module Soren; end

# source://soren//lib/soren/connection.rb#19
class Soren::Connection
  # : (?host: untyped, ?port: untyped, ?scheme: untyped, ?uri: untyped, ?options: untyped) -> void
  #
  # @return [Connection] a new instance of Connection
  #
  # source://soren//lib/soren/connection.rb#23
  def initialize(host: T.unsafe(nil), port: T.unsafe(nil), scheme: T.unsafe(nil), uri: T.unsafe(nil), options: T.unsafe(nil)); end

  # : -> (TCPSocket | OpenSSL::SSL::SSLSocket)
  #
  # source://soren//lib/soren/connection.rb#33
  def open_socket; end

  # : Soren::Options?
  #
  # source://soren//lib/soren/connection.rb#20
  def options; end

  # : (Soren::Request) -> Soren::Response
  #
  # source://soren//lib/soren/connection.rb#65
  def send(request); end

  private

  # : (Float?) -> TCPSocket
  #
  # source://soren//lib/soren/connection.rb#82
  def open_tcp_socket(timeout); end

  # : (host: untyped, port: untyped, scheme: untyped, uri: untyped) -> [untyped, untyped, untyped]
  #
  # source://soren//lib/soren/connection.rb#105
  def resolve_connection_parts(host:, port:, scheme:, uri:); end

  # : (OpenSSL::SSL::SSLSocket, Soren::Deadline?) -> void
  #
  # source://soren//lib/soren/connection.rb#87
  def ssl_connect_with_timeout(ssl, deadline); end
end

# source://soren//lib/soren/deadline.rb#5
class Soren::Deadline
  # : (Float) -> void
  #
  # @return [Deadline] a new instance of Deadline
  #
  # source://soren//lib/soren/deadline.rb#16
  def initialize(deadline_at); end

  # : -> bool
  #
  # @return [Boolean]
  #
  # source://soren//lib/soren/deadline.rb#27
  def expired?; end

  # : -> Float
  #
  # source://soren//lib/soren/deadline.rb#21
  def remaining; end

  class << self
    # : (Float?) -> Soren::Deadline?
    #
    # source://soren//lib/soren/deadline.rb#8
    def start(timeout); end
  end
end

# source://soren//lib/soren/decoders/gzip.rb#8
module Soren::Decoders; end

# source://soren//lib/soren/decoders/deflate.rb#8
class Soren::Decoders::Deflate
  # : (String) -> void
  #
  # @return [Deflate] a new instance of Deflate
  #
  # source://soren//lib/soren/decoders/deflate.rb#10
  def initialize(body); end

  # : -> String
  #
  # source://soren//lib/soren/decoders/deflate.rb#15
  def decode; end

  private

  # : -> String
  #
  # source://soren//lib/soren/decoders/deflate.rb#24
  def decode_raw_deflate; end
end

# source://soren//lib/soren/decoders/gzip.rb#9
class Soren::Decoders::Gzip
  # : (String) -> void
  #
  # @return [Gzip] a new instance of Gzip
  #
  # source://soren//lib/soren/decoders/gzip.rb#11
  def initialize(body); end

  # : -> String
  #
  # source://soren//lib/soren/decoders/gzip.rb#16
  def decode; end
end

# source://soren//lib/soren/defaults/options.rb#5
module Soren::Defaults; end

# source://soren//lib/soren/defaults/options.rb#6
module Soren::Defaults::Options; end

# source://soren//lib/soren/defaults/options.rb#8
Soren::Defaults::Options::CONNECT_TIMEOUT = T.let(T.unsafe(nil), Float)

# source://soren//lib/soren/defaults/options.rb#7
Soren::Defaults::Options::READ_TIMEOUT = T.let(T.unsafe(nil), Float)

# source://soren//lib/soren/defaults/options.rb#9
Soren::Defaults::Options::WRITE_TIMEOUT = T.let(T.unsafe(nil), Float)

# source://soren//lib/soren/error.rb#5
module Soren::Error; end

# source://soren//lib/soren/error/argument_error.rb#6
class Soren::Error::ArgumentError < ::Soren::Error::Base; end

# source://soren//lib/soren/error.rb#6
class Soren::Error::Base < ::StandardError; end

# source://soren//lib/soren/error/connection_error.rb#6
class Soren::Error::ConnectionError < ::Soren::Error::Base; end

# source://soren//lib/soren/error/connection_refused.rb#6
class Soren::Error::ConnectionRefused < ::Soren::Error::ConnectionError; end

# source://soren//lib/soren/error/dns_failure.rb#6
class Soren::Error::DNSFailure < ::Soren::Error::ConnectionError; end

# source://soren//lib/soren/error/parse_error.rb#6
class Soren::Error::ParseError < ::Soren::Error::Base; end

# source://soren//lib/soren/error/protocol_error.rb#6
class Soren::Error::ProtocolError < ::Soren::Error::Base; end

# source://soren//lib/soren/error/read_error.rb#6
class Soren::Error::ReadError < ::Soren::Error::Base; end

# source://soren//lib/soren/error/read_timeout.rb#6
class Soren::Error::ReadTimeout < ::Soren::Error::TimeoutError; end

# source://soren//lib/soren/error/ssl_error.rb#6
class Soren::Error::SSLError < ::Soren::Error::Base; end

# source://soren//lib/soren/error/timeout_error.rb#6
class Soren::Error::TimeoutError < ::Soren::Error::ConnectionError; end

# source://soren//lib/soren/error/write_timeout.rb#6
class Soren::Error::WriteTimeout < ::Soren::Error::TimeoutError; end

# source://soren//lib/soren/options.rb#8
class Soren::Options
  # : (?untyped) -> void
  #
  # @return [Options] a new instance of Options
  #
  # source://soren//lib/soren/options.rb#13
  def initialize(options = T.unsafe(nil)); end

  # : -> Float
  #
  # source://soren//lib/soren/options.rb#28
  def connect_timeout; end

  # : -> Float
  #
  # source://soren//lib/soren/options.rb#23
  def read_timeout; end

  # : -> Float
  #
  # source://soren//lib/soren/options.rb#33
  def write_timeout; end

  private

  # : (Symbol | String) -> Symbol
  #
  # @raise [Soren::Error::ArgumentError]
  #
  # source://soren//lib/soren/options.rb#61
  def normalize_key(key); end

  # : (untyped) -> Hash[Symbol, untyped]
  #
  # source://soren//lib/soren/options.rb#40
  def normalize_options(options); end
end

# source://soren//lib/soren/options.rb#9
Soren::Options::AVAILABLE_OPTIONS = T.let(T.unsafe(nil), Array)

# source://soren//lib/soren/parsers/response/status_line.rb#5
module Soren::Parsers; end

# source://soren//lib/soren/parsers/response/status_line.rb#6
class Soren::Parsers::Response
  # : (untyped, ?deadline: Deadline?) -> void
  #
  # @return [Response] a new instance of Response
  #
  # source://soren//lib/soren/parsers/response.rb#21
  def initialize(source, deadline: T.unsafe(nil)); end

  # : -> Hash[Symbol, untyped]
  #
  # source://soren//lib/soren/parsers/response.rb#27
  def parse; end

  private

  # : (Soren::Socket::Reader) -> Array[String]
  #
  # source://soren//lib/soren/parsers/response.rb#64
  def read_header_lines(reader); end
end

# source://soren//lib/soren/parsers/response/body.rb#12
class Soren::Parsers::Response::Body
  # : (reader: Soren::Socket::Reader, headers: Soren::Types::Response::Headers, code: Soren::Types::Response::Code) -> void
  #
  # @return [Body] a new instance of Body
  #
  # source://soren//lib/soren/parsers/response/body.rb#14
  def initialize(reader:, headers:, code:); end

  # : -> String
  #
  # source://soren//lib/soren/parsers/response/body.rb#21
  def parse; end

  private

  # : -> void
  #
  # source://soren//lib/soren/parsers/response/body.rb#89
  def consume_chunked_trailers; end

  # : (String) -> String
  #
  # source://soren//lib/soren/parsers/response/body.rb#48
  def decode_content_encodings(body); end

  # : -> bool
  #
  # @return [Boolean]
  #
  # source://soren//lib/soren/parsers/response/body.rb#43
  def no_body?; end

  # : -> String
  #
  # source://soren//lib/soren/parsers/response/body.rb#66
  def parse_chunked_body; end
end

# source://soren//lib/soren/parsers/response/headers.rb#7
class Soren::Parsers::Response::Headers
  # : (untyped) -> void
  #
  # @return [Headers] a new instance of Headers
  #
  # source://soren//lib/soren/parsers/response/headers.rb#9
  def initialize(header_lines); end

  # : -> Hash[String, Array[String]]
  #
  # source://soren//lib/soren/parsers/response/headers.rb#14
  def parse; end
end

# source://soren//lib/soren/parsers/response/status_line.rb#7
class Soren::Parsers::Response::StatusLine
  # : (untyped) -> void
  #
  # @return [StatusLine] a new instance of StatusLine
  #
  # source://soren//lib/soren/parsers/response/status_line.rb#9
  def initialize(status_line); end

  # : -> Hash[Symbol, untyped]
  #
  # source://soren//lib/soren/parsers/response/status_line.rb#14
  def parse; end
end

# source://soren//lib/soren/request.rb#10
class Soren::Request
  # : (method: untyped, target: untyped, ?headers: untyped, ?body: untyped) -> void
  #
  # @return [Request] a new instance of Request
  #
  # source://soren//lib/soren/request.rb#18
  def initialize(method:, target:, headers: T.unsafe(nil), body: T.unsafe(nil)); end

  # : Soren::Types::Request::Body?
  #
  # source://soren//lib/soren/request.rb#15
  def body; end

  # : Soren::Types::Request::Headers?
  #
  # source://soren//lib/soren/request.rb#14
  def headers; end

  # : Soren::Types::Request::Method?
  #
  # source://soren//lib/soren/request.rb#12
  def method; end

  # : Soren::Types::Request::Target?
  #
  # source://soren//lib/soren/request.rb#13
  def target; end

  # : (host: String) -> String
  #
  # source://soren//lib/soren/request.rb#26
  def to_http(host:); end
end

# source://soren//lib/soren/response.rb#11
class Soren::Response
  # : (Hash[Symbol, untyped]) -> void
  #
  # @return [Response] a new instance of Response
  #
  # source://soren//lib/soren/response.rb#38
  def initialize(parsed_response); end

  # : -> String
  #
  # source://soren//lib/soren/response.rb#33
  def body; end

  # : -> Integer
  #
  # source://soren//lib/soren/response.rb#13
  def code; end

  # : -> Hash[String, Array[String]]
  #
  # source://soren//lib/soren/response.rb#28
  def headers; end

  # : -> String
  #
  # source://soren//lib/soren/response.rb#18
  def message; end

  # : -> String
  #
  # source://soren//lib/soren/response.rb#23
  def version; end
end

# source://soren//lib/soren/socket/reader.rb#9
module Soren::Socket; end

# source://soren//lib/soren/socket/io.rb#11
class Soren::Socket::IO
  # : ((TCPSocket | OpenSSL::SSL::SSLSocket), Soren::Request, Soren::Options, host: Soren::Types::Connection::Host) -> void
  #
  # @return [IO] a new instance of IO
  #
  # source://soren//lib/soren/socket/io.rb#13
  def initialize(socket, request, options, host:); end

  # : -> Hash[Symbol, untyped]
  #
  # source://soren//lib/soren/socket/io.rb#42
  def read_response; end

  # : -> Integer
  #
  # source://soren//lib/soren/socket/io.rb#21
  def write_request; end

  private

  # : (StandardError, Deadline?) -> void
  #
  # @raise [Soren::Error::WriteTimeout]
  #
  # source://soren//lib/soren/socket/io.rb#50
  def handle_write_error(error, deadline); end

  # : (Float?) -> bool
  #
  # source://soren//lib/soren/socket/io.rb#58
  def wait_writable(timeout); end
end

# source://soren//lib/soren/socket/reader.rb#10
class Soren::Socket::Reader
  # : (untyped, ?deadline: Deadline?) -> void
  #
  # @return [Reader] a new instance of Reader
  #
  # source://soren//lib/soren/socket/reader.rb#12
  def initialize(source, deadline: T.unsafe(nil)); end

  # : -> String
  #
  # source://soren//lib/soren/socket/reader.rb#47
  def read_all; end

  # : (Integer) -> String
  #
  # source://soren//lib/soren/socket/reader.rb#30
  def read_exactly(length); end

  # : -> String?
  #
  # source://soren//lib/soren/socket/reader.rb#18
  def read_line; end

  # : (String) -> String?
  #
  # source://soren//lib/soren/socket/reader.rb#24
  def read_line_with_terminator(terminator); end

  private

  # : -> void
  #
  # @raise [Soren::Error::ReadTimeout]
  #
  # source://soren//lib/soren/socket/reader.rb#55
  def check_deadline_expired; end

  # : (untyped) -> untyped
  #
  # @raise [Soren::Error::ParseError]
  #
  # source://soren//lib/soren/socket/reader.rb#62
  def to_io(source); end
end

# source://soren//lib/soren/types/options/timeout/base.rb#5
module Soren::Types; end

# source://soren//lib/soren/types/connection/host.rb#6
module Soren::Types::Connection; end

# source://soren//lib/soren/types/connection/host.rb#7
class Soren::Types::Connection::Host
  # : (untyped) -> void
  #
  # @return [Host] a new instance of Host
  #
  # source://soren//lib/soren/types/connection/host.rb#9
  def initialize(host); end

  # : -> String
  #
  # source://soren//lib/soren/types/connection/host.rb#14
  def to_s; end

  private

  # : (String) -> bool
  #
  # @return [Boolean]
  #
  # source://soren//lib/soren/types/connection/host.rb#37
  def resolvable?(host); end

  # : (untyped) -> String
  #
  # @raise [Soren::Error::ArgumentError]
  #
  # source://soren//lib/soren/types/connection/host.rb#21
  def validate(host); end
end

# source://soren//lib/soren/types/connection/port.rb#7
class Soren::Types::Connection::Port
  # : (untyped) -> void
  #
  # @return [Port] a new instance of Port
  #
  # source://soren//lib/soren/types/connection/port.rb#9
  def initialize(port); end

  # : -> Integer
  #
  # source://soren//lib/soren/types/connection/port.rb#19
  def to_i; end

  # : -> String
  #
  # source://soren//lib/soren/types/connection/port.rb#14
  def to_s; end

  private

  # : (untyped) -> Integer
  #
  # source://soren//lib/soren/types/connection/port.rb#26
  def validate(port); end
end

# source://soren//lib/soren/types/connection/scheme.rb#7
class Soren::Types::Connection::Scheme
  # : (untyped) -> void
  #
  # @return [Scheme] a new instance of Scheme
  #
  # source://soren//lib/soren/types/connection/scheme.rb#9
  def initialize(scheme); end

  # : -> bool
  #
  # @return [Boolean]
  #
  # source://soren//lib/soren/types/connection/scheme.rb#19
  def https?; end

  # : -> String
  #
  # source://soren//lib/soren/types/connection/scheme.rb#14
  def to_s; end

  private

  # : (untyped) -> String
  #
  # source://soren//lib/soren/types/connection/scheme.rb#26
  def validate(scheme); end
end

# source://soren//lib/soren/types/connection/uri.rb#9
class Soren::Types::Connection::Uri
  # : (untyped) -> void
  #
  # @return [Uri] a new instance of Uri
  #
  # source://soren//lib/soren/types/connection/uri.rb#11
  def initialize(uri); end

  # : -> String?
  #
  # source://soren//lib/soren/types/connection/uri.rb#16
  def host; end

  # : -> Integer?
  #
  # source://soren//lib/soren/types/connection/uri.rb#21
  def port; end

  # : -> String?
  #
  # source://soren//lib/soren/types/connection/uri.rb#26
  def scheme; end

  private

  # : (untyped) -> URI::HTTP
  #
  # source://soren//lib/soren/types/connection/uri.rb#33
  def validate(uri); end
end

# source://soren//lib/soren/types/options/timeout/base.rb#6
module Soren::Types::Options; end

# source://soren//lib/soren/types/options/timeout/base.rb#7
module Soren::Types::Options::Timeout; end

# source://soren//lib/soren/types/options/timeout/base.rb#8
class Soren::Types::Options::Timeout::Base
  # : (Float | Integer | String | nil, ?default: Float?) -> void
  #
  # @return [Base] a new instance of Base
  #
  # source://soren//lib/soren/types/options/timeout/base.rb#10
  def initialize(timeout, default: T.unsafe(nil)); end

  # : -> Float
  #
  # source://soren//lib/soren/types/options/timeout/base.rb#16
  def to_f; end

  private

  # : (Float | Integer | String | nil) -> Float
  #
  # source://soren//lib/soren/types/options/timeout/base.rb#23
  def validate(timeout); end
end

# source://soren//lib/soren/types/options/timeout/connect_timeout.rb#11
class Soren::Types::Options::Timeout::ConnectTimeout < ::Soren::Types::Options::Timeout::Base
  # : (untyped) -> void
  #
  # @return [ConnectTimeout] a new instance of ConnectTimeout
  #
  # source://soren//lib/soren/types/options/timeout/connect_timeout.rb#13
  def initialize(timeout); end
end

# source://soren//lib/soren/types/options/timeout/read_timeout.rb#11
class Soren::Types::Options::Timeout::ReadTimeout < ::Soren::Types::Options::Timeout::Base
  # : (untyped) -> void
  #
  # @return [ReadTimeout] a new instance of ReadTimeout
  #
  # source://soren//lib/soren/types/options/timeout/read_timeout.rb#13
  def initialize(timeout); end
end

# source://soren//lib/soren/types/options/timeout/write_timeout.rb#11
class Soren::Types::Options::Timeout::WriteTimeout < ::Soren::Types::Options::Timeout::Base
  # : (untyped) -> void
  #
  # @return [WriteTimeout] a new instance of WriteTimeout
  #
  # source://soren//lib/soren/types/options/timeout/write_timeout.rb#13
  def initialize(timeout); end
end

# source://soren//lib/soren/types/request/target.rb#6
module Soren::Types::Request; end

# source://soren//lib/soren/types/request/body.rb#7
class Soren::Types::Request::Body
  # : (untyped) -> void
  #
  # @return [Body] a new instance of Body
  #
  # source://soren//lib/soren/types/request/body.rb#9
  def initialize(body); end

  # : -> String?
  #
  # source://soren//lib/soren/types/request/body.rb#19
  def to_http; end

  # : -> String?
  #
  # source://soren//lib/soren/types/request/body.rb#14
  def to_s; end

  private

  # : (untyped) -> String?
  #
  # source://soren//lib/soren/types/request/body.rb#26
  def validate(body); end
end

# source://soren//lib/soren/types/request/headers.rb#7
class Soren::Types::Request::Headers
  # : (untyped, ?content_length: Integer?) -> void
  #
  # @return [Headers] a new instance of Headers
  #
  # source://soren//lib/soren/types/request/headers.rb#9
  def initialize(headers, content_length: T.unsafe(nil)); end

  # : -> Hash[String, String]
  #
  # source://soren//lib/soren/types/request/headers.rb#14
  def to_h; end

  # : (host: untyped) -> Array[String]
  #
  # source://soren//lib/soren/types/request/headers.rb#19
  def to_http(host:); end

  private

  # : (untyped, content_length: Integer?) -> Hash[String, String]
  #
  # source://soren//lib/soren/types/request/headers.rb#35
  def validate(headers, content_length:); end
end

# source://soren//lib/soren/types/request/method.rb#7
class Soren::Types::Request::Method
  # : (untyped) -> void
  #
  # @return [Method] a new instance of Method
  #
  # source://soren//lib/soren/types/request/method.rb#11
  def initialize(method); end

  # : -> String
  #
  # source://soren//lib/soren/types/request/method.rb#21
  def to_http; end

  # : -> String
  #
  # source://soren//lib/soren/types/request/method.rb#16
  def to_s; end

  private

  # : (untyped) -> String
  #
  # source://soren//lib/soren/types/request/method.rb#28
  def validate(method); end
end

# source://soren//lib/soren/types/request/method.rb#8
Soren::Types::Request::Method::ALLOWED_METHODS = T.let(T.unsafe(nil), Array)

# source://soren//lib/soren/types/request/target.rb#7
class Soren::Types::Request::Target
  # : (untyped) -> void
  #
  # @return [Target] a new instance of Target
  #
  # source://soren//lib/soren/types/request/target.rb#9
  def initialize(target); end

  # : -> String
  #
  # source://soren//lib/soren/types/request/target.rb#19
  def to_http; end

  # : -> String
  #
  # source://soren//lib/soren/types/request/target.rb#14
  def to_s; end

  private

  # : (untyped) -> String
  #
  # source://soren//lib/soren/types/request/target.rb#26
  def validate(target); end
end

# source://soren//lib/soren/types/response/code.rb#6
module Soren::Types::Response; end

# source://soren//lib/soren/types/response/body.rb#7
class Soren::Types::Response::Body
  # : (untyped) -> void
  #
  # @return [Body] a new instance of Body
  #
  # source://soren//lib/soren/types/response/body.rb#9
  def initialize(body); end

  # : -> String
  #
  # source://soren//lib/soren/types/response/body.rb#14
  def to_s; end

  private

  # : (untyped) -> String
  #
  # source://soren//lib/soren/types/response/body.rb#21
  def validate(body); end
end

# source://soren//lib/soren/types/response/code.rb#7
class Soren::Types::Response::Code
  # : (untyped) -> void
  #
  # @return [Code] a new instance of Code
  #
  # source://soren//lib/soren/types/response/code.rb#12
  def initialize(code); end

  # : -> bool
  #
  # @return [Boolean]
  #
  # source://soren//lib/soren/types/response/code.rb#22
  def no_body?; end

  # : -> Integer
  #
  # source://soren//lib/soren/types/response/code.rb#17
  def to_i; end

  private

  # : (untyped) -> Integer
  #
  # source://soren//lib/soren/types/response/code.rb#29
  def validate(code); end
end

# source://soren//lib/soren/types/response/code.rb#9
Soren::Types::Response::Code::NOT_MODIFIED = T.let(T.unsafe(nil), Integer)

# source://soren//lib/soren/types/response/code.rb#8
Soren::Types::Response::Code::NO_CONTENT = T.let(T.unsafe(nil), Integer)

# source://soren//lib/soren/types/response/headers.rb#7
class Soren::Types::Response::Headers
  # : (untyped) -> void
  #
  # @return [Headers] a new instance of Headers
  #
  # source://soren//lib/soren/types/response/headers.rb#9
  def initialize(headers); end

  # : -> bool
  #
  # @return [Boolean]
  #
  # source://soren//lib/soren/types/response/headers.rb#36
  def chunked?; end

  # : -> Array[String]
  #
  # source://soren//lib/soren/types/response/headers.rb#51
  def content_encodings; end

  # : -> Integer?
  #
  # source://soren//lib/soren/types/response/headers.rb#26
  def content_length; end

  # : (untyped) -> Array[String]
  #
  # source://soren//lib/soren/types/response/headers.rb#19
  def get_all(key); end

  # : -> bool
  #
  # @return [Boolean]
  #
  # source://soren//lib/soren/types/response/headers.rb#41
  def keep_alive?; end

  # : -> Hash[String, Array[String]]
  #
  # source://soren//lib/soren/types/response/headers.rb#14
  def to_h; end

  private

  # : (Array[String]) -> Array[String]
  #
  # source://soren//lib/soren/types/response/headers.rb#78
  def split_header_values(values); end

  # : (untyped) -> Hash[String, Array[String]]
  #
  # source://soren//lib/soren/types/response/headers.rb#58
  def validate(headers); end
end

# source://soren//lib/soren/types/response/message.rb#7
class Soren::Types::Response::Message
  # : (untyped) -> void
  #
  # @return [Message] a new instance of Message
  #
  # source://soren//lib/soren/types/response/message.rb#9
  def initialize(message); end

  # : -> String
  #
  # source://soren//lib/soren/types/response/message.rb#14
  def to_s; end

  private

  # : (untyped) -> String
  #
  # source://soren//lib/soren/types/response/message.rb#21
  def validate(message); end
end

# source://soren//lib/soren/types/response/version.rb#7
class Soren::Types::Response::Version
  # : (untyped) -> void
  #
  # @return [Version] a new instance of Version
  #
  # source://soren//lib/soren/types/response/version.rb#9
  def initialize(version); end

  # : -> String
  #
  # source://soren//lib/soren/types/response/version.rb#14
  def to_s; end

  private

  # : (untyped) -> String
  #
  # source://soren//lib/soren/types/response/version.rb#21
  def validate(version); end
end

# source://soren//lib/soren/version.rb#4
Soren::VERSION = T.let(T.unsafe(nil), String)

# source://soren//lib/soren/core_ext/blank.rb#18
class String
  include ::Comparable
end
